- app/views/home/index.html.haml
Thoses where displayed on Chrome
https://bugs.chromium.org/p/chromium/issues/detail?id=550275
http://www.fileformat.info/info/unicode/char/2028/index.htm
> Remove the useless & displayed (on Chrome) L SEP on Home

- app/views/trips/show.html.haml
Fix #covoiturage-libre/covoiturage-libre/issues/150
http://stackoverflow.com/questions/3137393/rails-add-a-line-break-into-a-text-area
> Fix commentaires enregistrees sur plusieurs lignes

- app/mailers/user_mailer.rb
Add and use an ENV var `MAILER_SUBJECT_PREFIX` for mailers.
To reuse the app on other projects
To test : edit it and send a test mail via `UserMailer.message_sent_notification(Message.new(trip: Trip.new(email "you@example.com")).deliver`
> Factorize mailer subject formatting

- app/models/trip.rb
Bonjour,
petite contribution pour les issues #133 et #143
> Etapes ordonnancées. #133

- app/models/message.rb
- app/models/trip.rb
- app/validators/email_validator.rb
fixes the main problem of #157 and is good practice anyway in my opinion.
I reused the simple check of @thb.
maybe we should make a proper function for it. But I don't know where I should put it in a Rail project.
> validate email format before responding to announce

- app/mailers/application_mailer.rb
- app/mailers/user_mailer.rb
- spec/factories/cities.rb
- spec/factories/messages.rb
- spec/factories/points.rb
- spec/mailers/previews/user_mailer_preview.rb
Add and use an ENV var `MAILER_FROM ` for mailers.
To reuse the app on other projects
To test : edit it and send a test mail via `ApplicationMailer.mail(to: "you@example.com", subject: "test", body: "test").deliver`
Check mail previews on http://localhost:3000/rails/mailers
> Add MAILER_FROM env config

- app/models/point.rb
- app/views/trips/show.html.haml
Add a validation for steps prices to be greater to 0.
> Prix negatifs 165

- Dockerfile
- docker-compose.yml
Hi @wayglem @Poussinou @pimpin 
I fixed the docker build, steps to check the pull request :
1. (install and launch docker)
2. Run `docker-compose up --build`
3. Check on http://localhost:3000/
Regards
> Add Docker and docker-compose #164

- app/views/layouts/application.html.haml
See issue at https://github.com/covoiturage-libre/covoiturage-libre/issues/145
> Fix HTML validation #145

- config/secrets.yml
Deployment was broken as there was no secret key base set for the staging mode.
I just added two lines to get it from ENV variable.
> secret base from ENV

- lib/tasks/db.rake
https://github.com/covoiturage-libre/covoiturage-libre/issues/199
> Guard db:enable_postgis to avoid exception if already #199

- app/assets/stylesheets/_home.scss
- app/views/search/_form.html.haml
To test :
1. Go on http://localhost:3000/recherche?utf8=%E2%9C%93&search%5Bfrom_city%5D=Paris&search%5Bfrom_lon%5D=2.333333&search%5Bfrom_lat%5D=48.866667&search%5Bto_city%5D=Dijon&search%5Bto_lon%5D=5.016667&search%5Bto_lat%5D=47.316667&search%5Bdate%5D=&commit=Rechercher
2. Click on the switch button then search
3. You must see the parameters in URL and input values inverted
> Add City switch button in Search #129

- app/validators/prices_validator.rb
Small fix to prevent server error in price validator.
Was crashing when price was not specified.
This is useful for sortable steps #182
> fix internal server error on nil price

- app.json
- Auto enable `delayedjob` dyno for mails.
- Try a deploy on Heroku via  https://heroku.com/deploy?template=https://github.com/nicolasleger/covoiturage-libre/tree/enhance_heroku_app_json
> Precise dyno formation for Heroku app.json

- .travis.yml
- README.md
- spec/features/user_signin_feature_spec.rb
- spec/features/user_signup_feature_spec.rb
- spec/mailers/user_mailer_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- Fix tests by fixing configuration and disabled deprecated ones
- Add Travis CI to execute test automatically and display a badge in the ReadMe
- `bundle exec rspec`
> Fix tests and add Travis CI

- docker-compose.yml
- All in title
- docker compose one time then restart your docker host to check if container are not already running
> Disable Docker compose services auto restart

- app/views/home/index.html.haml
Question mark was displaced on medium screens.
> fix nbsp on homepage

- app/views/trips/_trip.html.haml
Now that trips can have zero available seats, show "Complet" in the search results too.
> showing complet in search results too

- app/models/point.rb
- app/validators/prices_validator.rb
- spec/validators/prices_validator_spec.rb
Issue https://github.com/covoiturage-libre/covoiturage-libre/issues/233
> Guard and add tests on PricesValidator

- docker-compose.yml
> Fix Docker compose versions like production env

- app/controllers/cities_controller.rb
See https://github.com/covoiturage-libre/covoiturage-libre/issues/230
> Fix main cities order in search results #219 #230

- docker-compose.yml
- wait-for-it.sh
> Fix Docker Compose databases links

- config/environments/development.rb
Avoid console error `Cannot render console from 172.19.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255` when using Docker compose.
See https://github.com/rails/web-console#configweb_consolewhiny_requests
> Allow console display for Docker

- docker-compose.yml
> Fix Docker compose

- app.json
- app/views/layouts/_sentry_raven.html.erb
- app/views/layouts/application.html.haml
- config/initializers/sentry_raven.rb
- scalingo.json
> Use conventional SENTRY_DSN instead of SENTRY_RAVEN_DSN

- app/views/layouts/_slaask.html.erb
> Avoid Slaask reloading on page change

- app/controllers/cities_controller.rb
- app/models/city.rb
Issue https://github.com/covoiturage-libre/covoiturage-libre/issues/239 and https://github.com/covoiturage-libre/covoiturage-libre/issues/230
> Fix Cities boosting prefix, main, and French

- scalingo.json
See https://scalingo.com/articles/2017/11/24/scalingo-json-formation.html
Scalingo deploy button
> Precise Container Formation for Scalingo deploy

- docker-compose.yml
> Update Redis to 4.0.1

- app/views/layouts/application.html.haml
The official account is https://twitter.com/CovoitLibre
> Fix Twitter meta link

- docker-compose.yml
> Use worker term in Docker for delayed_job

- Procfile
>  Use worker term in Procfile for delayed_job

- docker-compose.yml
> Update Postgis to 10 in Docker like production

- app/views/home/index.html.haml
> Hotfix homepage

- app/views/trips/_trip.html.haml
> Hotfix search

- app/views/trips/_trip.html.haml
> Hotfix search 2

- Gemfile
- Gemfile.lock
- spec/factories/cities.rb
- spec/factories/messages.rb
- spec/factories/points.rb
- spec/factories/trips.rb
- spec/factories/users.rb
- spec/features/user_signup_feature_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md
> Use new FactoryBot instead of FactoryGirl

- Gemfile.lock
Fix Ruby `2.5.0` launch in `production` mode with `Devise` dependency.
See https://github.com/plataformatec/devise/blob/master/CHANGELOG.md#440---2017-12-29
> Update devise gem for Ruby 2.5.0

- app.json
> Fix Heroku formation dyno type

- app/views/trips/show.html.haml
Fix (past) trip display when no seats count specified (now mandatory).
See error https://sentry.tymate.com/tymate/covoiturage-libre-production/issues/1495/
For the Trip at https://covoiturage-libre.fr/trajets/Af2v2hI0SAawTupYxVhpiI6mD
> Fix Trip display without seats

- app/validators/prices_validator.rb
- spec/validators/prices_validator_spec.rb
> Fix PricesValidator with empty Points rnak

- spec/factories/trips.rb
> Fix Trips controller spec

- app/views/trips/phones/show.html.erb
- app/views/trips/phones/show.js.erb
Avoid error on https://covoiturage-libre.fr/trajets/uwmfwzryzcubcu8gctxb5mve/phone
> Guard Trip phone page display

- .gitignore
> Ignore local Redis database [ci skip]

- Procfile
Ensure database is ready on Heroku deployments.
> Auto migrate DB on Heroku via Procfile

- Procfile
- app.json
> Fix Heroku first deploy via button

- .rubocop.yml
To fix miss-leading auto code review from Codacy tool : `unexpected token error (Using Ruby 2.1 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)`
See https://app.codacy.com/app/nicolasleger/covoiturage-libre/pullRequest?prid=1324678&/login for example
> Ensure Codacy Rubocop use 2.5 syntax

- Gemfile
- Gemfile.lock
- config/initializers/locale.rb
- spec/controllers/trips_controller_spec.rb
> Update development and test gems

- .travis.yml
> [CI] Clean Travis config

- app/assets/javascripts/_init-autocomplete.js
- app/views/search/_form.html.haml
Fix https://github.com/covoiturage-libre/covoiturage-libre/issues/193
> fix(193) Display error message on top city input

- Gemfile.lock
Fix CVE-2018-8048 https://github.com/flavorjones/loofah/issues/144
> Patch loofah gem CVE-2018-8048

- Gemfile.lock
> Patch Ruby 2.5.1

- config/routes.rb
Fix https://sentry.tymate.com/tymate/covoiturage-libre-development/issues/1997/
> Fix cities default JSON format

- app/models/trip.rb
> Fix Trip default scope

- app/controllers/admin/page_parts_controller.rb
- app/controllers/admin/pages_controller.rb
> Update before_filter with new Rails before_action

- app/assets/stylesheets/_home.scss
- app/controllers/search_controller.rb
- app/views/search/index.html.haml
plain text date for the mini calendar
#192
> Better search results : plain text date for the mini calendar
